### ISSUE TITLE
Feature Request- Display Predicted Time of completion.

### ISSUE THREAD

**Issue by rubyredrick** [eyal0/OctoPrint-PrintTimeGenius#266] opened 2021-09-05 18:10 UTC
I know I can do this mentally by adding the print time left to the wall clock.  But even a Raspberry Pi should be able to do that faster than I can, with or without a hardware real time clock if it’s connected to the internet.

I took a quick look at the code, but I need some pointers on how to try to add this and make a pull request.

**Comment by eyal0** [comment] 2021-09-06 04:19
Duplicate of #265 ?

**Closed by eyal0** 2021-09-06 04:19 UTC
