### ISSUE TITLE
[Feature Request]: Add estimated completion time

### ISSUE THREAD

**Issue by ShaneF1** [eyal0/OctoPrint-PrintTimeGenius#196] opened 2020-05-21 06:52 UTC
I find the time left estimates to be quite good and as I am printing quite a lot I find myself constantly converting the estimated print time at the beginning of a print to estimated completion time (ie: 2020-05-21 19:41). 

At the start of a print I really just want to know when it will finish. Estimated print time left is really useful (to me) at the end of a print when I am waiting and wanting to know "how long to go".

I suggest a useful and convenient feature would be to supplement the estimated print time left with a completion estimate. I have no idea if it is possible to suffix this after the time left estimate or if it would need to be displayed elsewhere..

**Comment by eyal0** [comment] 2020-05-27 19:28
This is a duplicate of #178 .

Please re-open this bug if the solution in that one doesn't suit you.

**Closed by eyal0** 2020-05-27 19:28 UTC
