### ISSUE TITLE
[Feature Request] - ETA or Estimated Time at end of print

### ISSUE THREAD

**Issue by donatonasc** [eyal0/OctoPrint-PrintTimeGenius#260] opened 2021-06-30 14:33 UTC
Would this be hard to implement? Just adding the time to finish the print to the current time and getting the estimated time for when the print will be done?

**Comment by eyal0** [comment] 2021-07-03 03:27
This is a duplicate of #229 .  Please re-open this issue if you find that the solution in #229 is not sufficient for you.

**Closed by eyal0** 2021-07-03 03:27 UTC
