### ISSUE TITLE
[Feature Request] Local Time when Finished

### ISSUE THREAD

**Issue by Grafton1046** [eyal0/OctoPrint-PrintTimeGenius#259] opened 2021-06-09 03:46 UTC
Would it be possible to add a calculation of what time it would be when the print job is finished? 
Something like "Estimated print time: 21:15:21 (7:15:21 PM)

**Comment by eyal0** [comment] 2021-06-09 12:37
Duplicate of #229

**Closed by eyal0** 2021-06-09 12:37 UTC
